package com.objects.character.physical.species.artiodactyla;


import com.Global.*;
import com.objects.character.physical.species.Species;
import com.objects.character.physical.species.nomenclature.AnimalNameContainers;

import static com.objects.character.physical.species.artiodactyla.Bovidae.*;
import static com.objects.character.physical.species.artiodactyla.Suidae.*;
import static com.objects.character.physical.species.artiodactyla.Cervidae.*;

public class ArtiodactylaSpecies {
    // =========================================================================
    // BOVIDAE
    // =========================================================================

    public static final Species DOMESTIC_COW = Species.builder("domestic_cow", "Bos Taurus", "Domestic Cow")
            .addValidProperty(BOVIDAE_BODY)
            .addValidProperty(BOVIDAE_SKIN)
            .addValidProperty(BOVIDAE_FUR)
            .addValidProperty(BOVIDAE_HEAD)
            .addValidProperty(BOVIDAE_EYES)
            .addValidProperty(BOVIDAE_EARS)
            .addValidProperty(BOVIDAE_NOSE)
            .addValidProperty(BOVIDAE_MOUTH)
            .addValidProperty(BOVIDAE_HORN)
            .addValidProperty(BOVIDAE_NECK)
            .addValidProperty(BOVIDAE_TORSO)
            .addValidProperty(BOVIDAE_BACK)
            .addValidProperty(BOVIDAE_TAIL)
            .addValidProperty(BOVIDAE_UDDER)
            .addValidProperty(BOVIDAE_FRONT_HOOVES)
            .addValidProperty(BOVIDAE_REAR_HOOVES)
            .addValidProperty(BOVIDAE_BRAIN)
            .addValidProperty(BOVIDAE_VITAL_ORGANS)
            .addValidProperty(BOVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(BOVIDAE_DIGESTIVE)
            .addValidProperty(BOVIDAE_RESPIRATORY)
            .addValidProperty(BOVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(35)
            .setNomenclature(AnimalNameContainers.COW)
            .setLifeExpectancy(20)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(15)
            .setAgeOfInfertilityMale(18)
            .setAgeOfInfertilityFemale(18)
            .addGenderRatio(BOVIDAE_BODY_SIZE, 1.5f)
            .addGenderRatio(BOVIDAE_UDDER_SIZE, 0.0f)
            .build();

    public static final Species AMERICAN_BISON = Species.builder("american_bison", "Bison Bison Bison", "American Bison")
            .addValidProperty(BOVIDAE_BODY)
            .addValidProperty(BOVIDAE_SKIN)
            .addValidProperty(BOVIDAE_FUR)
            .addValidProperty(BOVIDAE_HEAD)
            .addValidProperty(BOVIDAE_EYES)
            .addValidProperty(BOVIDAE_EARS)
            .addValidProperty(BOVIDAE_NOSE)
            .addValidProperty(BOVIDAE_MOUTH)
            .addValidProperty(BOVIDAE_HORN)
            .addValidProperty(BOVIDAE_NECK)
            .addValidProperty(BOVIDAE_TORSO)
            .addValidProperty(BOVIDAE_BACK)
            .addValidProperty(BOVIDAE_TAIL)
            .addValidProperty(BOVIDAE_UDDER)
            .addValidProperty(BOVIDAE_FRONT_HOOVES)
            .addValidProperty(BOVIDAE_REAR_HOOVES)
            .addValidProperty(BOVIDAE_BRAIN)
            .addValidProperty(BOVIDAE_VITAL_ORGANS)
            .addValidProperty(BOVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(BOVIDAE_DIGESTIVE)
            .addValidProperty(BOVIDAE_RESPIRATORY)
            .addValidProperty(BOVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(35)
            .setNomenclature(AnimalNameContainers.BUFFALO)
            .setLifeExpectancy(25)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(3)
            .setAgeOfElderly(20)
            .setAgeOfInfertilityMale(23)
            .setAgeOfInfertilityFemale(20)
            .addGenderRatio(BOVIDAE_BODY_SIZE, 1.5f)
            .addGenderRatio(BOVIDAE_UDDER_SIZE, 0.0f)
            .build();

    public static final Species DOMESTIC_SHEEP = Species.builder("domestic_sheep", "Ovis Aries", "Domestic Sheep")
            .addValidProperty(BOVIDAE_BODY)
            .addValidProperty(BOVIDAE_SKIN)
            .addValidProperty(BOVIDAE_FUR)
            .addValidProperty(BOVIDAE_HEAD)
            .addValidProperty(BOVIDAE_EYES)
            .addValidProperty(BOVIDAE_EARS)
            .addValidProperty(BOVIDAE_NOSE)
            .addValidProperty(BOVIDAE_MOUTH)
            .addValidProperty(BOVIDAE_HORN)
            .addValidProperty(BOVIDAE_NECK)
            .addValidProperty(BOVIDAE_TORSO)
            .addValidProperty(BOVIDAE_BACK)
            .addValidProperty(BOVIDAE_TAIL)
            .addValidProperty(BOVIDAE_UDDER)
            .addValidProperty(BOVIDAE_FRONT_HOOVES)
            .addValidProperty(BOVIDAE_REAR_HOOVES)
            .addValidProperty(BOVIDAE_BRAIN)
            .addValidProperty(BOVIDAE_VITAL_ORGANS)
            .addValidProperty(BOVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(BOVIDAE_DIGESTIVE)
            .addValidProperty(BOVIDAE_RESPIRATORY)
            .addValidProperty(BOVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(25)
            .setNomenclature(AnimalNameContainers.SHEEP)
            .setLifeExpectancy(12)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(10)
            .setAgeOfInfertilityMale(11)
            .setAgeOfInfertilityFemale(10)
            .addGenderRatio(BOVIDAE_BODY_SIZE, 1.2f)
            .addGenderRatio(BOVIDAE_UDDER_SIZE, 0.0f)
            .build();

    public static final Species DOMESTIC_GOAT = Species.builder("domestic_goat", "Capra Hircus", "Domestic Goat")
            .addValidProperty(BOVIDAE_BODY)
            .addValidProperty(BOVIDAE_SKIN)
            .addValidProperty(BOVIDAE_FUR)
            .addValidProperty(BOVIDAE_HEAD)
            .addValidProperty(BOVIDAE_EYES)
            .addValidProperty(BOVIDAE_EARS)
            .addValidProperty(BOVIDAE_NOSE)
            .addValidProperty(BOVIDAE_MOUTH)
            .addValidProperty(BOVIDAE_HORN)
            .addValidProperty(BOVIDAE_NECK)
            .addValidProperty(BOVIDAE_TORSO)
            .addValidProperty(BOVIDAE_BACK)
            .addValidProperty(BOVIDAE_TAIL)
            .addValidProperty(BOVIDAE_UDDER)
            .addValidProperty(BOVIDAE_FRONT_HOOVES)
            .addValidProperty(BOVIDAE_REAR_HOOVES)
            .addValidProperty(BOVIDAE_BRAIN)
            .addValidProperty(BOVIDAE_VITAL_ORGANS)
            .addValidProperty(BOVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(BOVIDAE_DIGESTIVE)
            .addValidProperty(BOVIDAE_RESPIRATORY)
            .addValidProperty(BOVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(40)
            .setNomenclature(AnimalNameContainers.GOAT)
            .setLifeExpectancy(15)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(12)
            .setAgeOfInfertilityMale(14)
            .setAgeOfInfertilityFemale(13)
            .addGenderRatio(BOVIDAE_BODY_SIZE, 1.15f)
            .addGenderRatio(BOVIDAE_UDDER_SIZE, 0.0f)
            .build();

    // =========================================================================
    // SUIDAE
    // =========================================================================

    public static final Species DOMESTIC_PIG = Species.builder("domestic_pig", "Sus Scrofa Domesticus", "Domestic Pig")
            .addValidProperty(SUIDAE_BODY)
            .addValidProperty(SUIDAE_SKIN)
            .addValidProperty(SUIDAE_BRISTLES)
            .addValidProperty(SUIDAE_HEAD)
            .addValidProperty(SUIDAE_EYES)
            .addValidProperty(SUIDAE_EARS)
            .addValidProperty(SUIDAE_SNOUT)
            .addValidProperty(SUIDAE_MOUTH)
            .addValidProperty(SUIDAE_TUSKS)
            .addValidProperty(SUIDAE_NECK)
            .addValidProperty(SUIDAE_TORSO)
            .addValidProperty(SUIDAE_BACK)
            .addValidProperty(SUIDAE_TAIL)
            .addValidProperty(SUIDAE_FRONT_TROTTERS)
            .addValidProperty(SUIDAE_REAR_TROTTERS)
            .addValidProperty(SUIDAE_BRAIN)
            .addValidProperty(SUIDAE_VITAL_ORGANS)
            .addValidProperty(SUIDAE_IMMUNE_SYSTEM)
            .addValidProperty(SUIDAE_DIGESTIVE)
            .addValidProperty(SUIDAE_RESPIRATORY)
            .addValidProperty(SUIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(62)
            .setNomenclature(AnimalNameContainers.PIG)
            .setLifeExpectancy(15)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(1)
            .setAgeOfElderly(12)
            .setAgeOfInfertilityMale(14)
            .setAgeOfInfertilityFemale(13)
            .addGenderRatio(SUIDAE_BODY_SIZE, 1.1f)
            .addGenderRatio(SUIDAE_TUSK_SIZE, 1.6f)
            .build();

    // =========================================================================
    // CERVIDAE
    // =========================================================================

    public static final Species MOOSE = Species.builder("moose", "Alces Alces Americanus", "Moose")
            .addValidProperty(CERVIDAE_BODY)
            .addValidProperty(CERVIDAE_SKIN)
            .addValidProperty(CERVIDAE_FUR)
            .addValidProperty(CERVIDAE_HEAD)
            .addValidProperty(CERVIDAE_EYES)
            .addValidProperty(CERVIDAE_EARS)
            .addValidProperty(CERVIDAE_NOSE)
            .addValidProperty(CERVIDAE_MOUTH)
            .addValidProperty(CERVIDAE_ANTLERS)
            .addValidProperty(CERVIDAE_NECK)
            .addValidProperty(CERVIDAE_DEWLAP)
            .addValidProperty(CERVIDAE_TORSO)
            .addValidProperty(CERVIDAE_BACK)
            .addValidProperty(CERVIDAE_TAIL)
            .addValidProperty(CERVIDAE_FRONT_HOOVES)
            .addValidProperty(CERVIDAE_REAR_HOOVES)
            .addValidProperty(CERVIDAE_BRAIN)
            .addValidProperty(CERVIDAE_VITAL_ORGANS)
            .addValidProperty(CERVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CERVIDAE_DIGESTIVE)
            .addValidProperty(CERVIDAE_RESPIRATORY)
            .addValidProperty(CERVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(35)
            .setNomenclature(AnimalNameContainers.MOOSE)
            .setLifeExpectancy(20)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(15)
            .setAgeOfInfertilityMale(18)
            .setAgeOfInfertilityFemale(17)
            .addGenderRatio(CERVIDAE_BODY_SIZE, 1.4f)
            .addGenderRatio(CERVIDAE_ANTLER_SIZE, 2.0f)
            .build();

    public static final Species WHITE_TAILED_DEER = Species.builder("white_tailed_deer", "Odocoileus Virginianus", "White-tailed Deer")
            .addValidProperty(CERVIDAE_BODY)
            .addValidProperty(CERVIDAE_SKIN)
            .addValidProperty(CERVIDAE_FUR)
            .addValidProperty(CERVIDAE_HEAD)
            .addValidProperty(CERVIDAE_EYES)
            .addValidProperty(CERVIDAE_EARS)
            .addValidProperty(CERVIDAE_NOSE)
            .addValidProperty(CERVIDAE_MOUTH)
            .addValidProperty(CERVIDAE_ANTLERS)
            .addValidProperty(CERVIDAE_NECK)
            .addValidProperty(CERVIDAE_TORSO)
            .addValidProperty(CERVIDAE_BACK)
            .addValidProperty(CERVIDAE_TAIL)
            .addValidProperty(CERVIDAE_FRONT_HOOVES)
            .addValidProperty(CERVIDAE_REAR_HOOVES)
            .addValidProperty(CERVIDAE_BRAIN)
            .addValidProperty(CERVIDAE_VITAL_ORGANS)
            .addValidProperty(CERVIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CERVIDAE_DIGESTIVE)
            .addValidProperty(CERVIDAE_RESPIRATORY)
            .addValidProperty(CERVIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(30)
            .setNomenclature(AnimalNameContainers.DEER)
            .setLifeExpectancy(15)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(12)
            .setAgeOfInfertilityMale(14)
            .setAgeOfInfertilityFemale(13)
            .addGenderRatio(CERVIDAE_BODY_SIZE, 1.3f)
            .addGenderRatio(CERVIDAE_ANTLER_SIZE, 2.0f)
            .build();
    }
