package com.objects.character.physical.species.human;

import com.objects.character.physical.aspect.BodyPart;
import com.objects.character.physical.aspect.PhysicalAspect;
import com.objects.character.physical.species.creature.CreatureAugments;
import com.objects.character.physical.species.creature.CreatureGeneProperties;

public class HumanPhysicalAspects {
    public static final PhysicalAspect HUMAN_EYES = PhysicalAspect.Builder(BodyPart.EYES, "human_eye", "Human Eyes", "")
            .addValidProperty(HumanGeneProperties.HUMAN_EYE_COLOR)
            .addValidProperty(HumanGeneProperties.HUMAN_HETEROCHROMIA)
            .addValidProperty(HumanGeneProperties.HUMAN_EYE_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(HumanAugments.FALSE_EYE)
            .addValidAugment(HumanAugments.BIONIC_EYE)
            .addValidAugment(HumanAugments.GLASSES)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_HEAD = PhysicalAspect.Builder(BodyPart.HEAD, "human_head", "Human Head", "")
            .addValidProperty(HumanGeneProperties.HUMAN_HEAD_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_BODY_FACE = PhysicalAspect.Builder(BodyPart.FACE, "human_face", "Human Face", "")
            .addValidProperty(HumanGeneProperties.HUMAN_SKIN_FRECKLES)
            .addValidProperty(HumanGeneProperties.HUMAN_WRINKLE_AGE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_NECK = PhysicalAspect.Builder(BodyPart.NECK, "human_neck", "Human Neck", "")
            .addValidProperty(HumanGeneProperties.HUMAN_NECK_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_BODY_SKIN = PhysicalAspect.Builder(BodyPart.SKIN, "human_skin", "Human Skin", "")
            .addValidProperty(HumanGeneProperties.HUMAN_SKIN_MELANIN)
            .addValidProperty(HumanGeneProperties.HUMAN_SKIN_FRECKLES)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(HumanAugments.SKIN_TEXTURE)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_HEAD_HAIR = PhysicalAspect.Builder(BodyPart.HEAD_HAIR, "human_hair", "Human Hair", "")
            .addValidProperty(HumanGeneProperties.HUMAN_HAIR_COLOR)
            .addValidProperty(HumanGeneProperties.HUMAN_HAIR_CURL)
            .addValidProperty(HumanGeneProperties.HUMAN_HAIR_THICKNESS)
            .addValidProperty(HumanGeneProperties.HUMAN_GRAY_AGE)
            .addValidProperty(HumanGeneProperties.HUMAN_HAIR_BALDING_AGE)
            .addValidAugment(HumanAugments.HUMAN_HAIRCUT)
            .addValidAugment(CreatureAugments.LOSS)
            .build();
    public static final PhysicalAspect HUMAN_BODY = PhysicalAspect.Builder(BodyPart.WHOLE_BODY, "human_body", "Human Body", "")
            .addValidProperty(HumanGeneProperties.HUMAN_HEIGHT)
            .addValidProperty(HumanGeneProperties.HUMAN_WEIGHT)
            .addValidProperty(HumanGeneProperties.HUMAN_BODY_HAIR)
            .addValidProperty(HumanGeneProperties.HUMAN_BODY_SHAPE)
            .addValidProperty(HumanGeneProperties.HUMAN_T_GENE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_REPRODUCTIVE = PhysicalAspect.Builder(BodyPart.GENITAL, "human_reproductive", "Human Reproductive Organ", "")
            .addValidProperty(HumanGeneProperties.HUMAN_GENITAL)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(CreatureGeneProperties.INFERTILITY)
            .addValidAugment(HumanAugments.STERILIZATION)
            .addValidAugment(HumanAugments.CASTRATION)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_TORSO = PhysicalAspect.Builder(BodyPart.TORSO, "human_torso", "Human Torso", "")
            .addValidProperty(HumanGeneProperties.HUMAN_BREASTS)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_ARMS = PhysicalAspect.Builder(BodyPart.ARMS, "human_arms", "Human Arms", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(HumanGeneProperties.HUMAN_WRINKLE_AGE)
            .addValidAugment(HumanAugments.BIONIC_ARM)
            .addValidAugment(HumanAugments.PROSTHETIC_ARM)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PARALYSIS)
            .build();
    public static final PhysicalAspect HUMAN_LEGS = PhysicalAspect.Builder(BodyPart.LEGS, "human_legs", "Human Legs", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(HumanGeneProperties.HUMAN_WRINKLE_AGE)
            .addValidAugment(HumanAugments.BIONIC_LEG)
            .addValidAugment(HumanAugments.PROSTHETIC_LEG)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PARALYSIS)
            .build();
    public static final PhysicalAspect HUMAN_BACK = PhysicalAspect.Builder(BodyPart.BACK, "human_back", "Human Back", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_CHEST = PhysicalAspect.Builder(BodyPart.CHEST, "human_chest", "Human Chest", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_PELVIS = PhysicalAspect.Builder(BodyPart.PELVIS, "human_pelvis", "Human Pelvis", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_FACIAL_HAIR = PhysicalAspect.Builder(BodyPart.FACIAL_HAIR, "human_facial_hair", "Human Facial Hair", "")
            .addValidAugment(HumanAugments.HUMAN_BEARD)
            .addValidAugment(CreatureAugments.LOSS)
            .build();
    public static final PhysicalAspect HUMAN_BODY_HAIR_ASPECT = PhysicalAspect.Builder(BodyPart.BODY_HAIR, "human_body_hair", "Human Body Hair", "")
            .addValidAugment(HumanAugments.HUMAN_BODY_HAIR_GROOMING)
            .addValidAugment(CreatureAugments.LOSS)
            .build();
    public static final PhysicalAspect HUMAN_SHOULDERS = PhysicalAspect.Builder(BodyPart.SHOULDERS, "human_shoulders", "Human Shoulders", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.PHYSIQUE)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_NOSE = PhysicalAspect.Builder(BodyPart.NOSE, "human_nose", "Human Nose", "")
            .addValidProperty(HumanGeneProperties.HUMAN_NOSE_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_MOUTH = PhysicalAspect.Builder(BodyPart.MOUTH, "human_mouth", "Human Mouth", "")
            .addValidProperty(HumanGeneProperties.HUMAN_MOUTH_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_EARS = PhysicalAspect.Builder(BodyPart.EARS, "human_ears", "Human Ears", "")
            .addValidProperty(HumanGeneProperties.HUMAN_EAR_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PIERCING)
            .build();
    public static final PhysicalAspect HUMAN_TEETH = PhysicalAspect.Builder(BodyPart.TEETH, "human_teeth", "Human Teeth", "")
            .addValidProperty(HumanGeneProperties.HUMAN_TOOTH_SHAPE)
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(HumanAugments.TEETH_CONDITION)
            .addValidAugment(HumanAugments.TEETH_BRACES)
            .addValidAugment(HumanAugments.TEETH_IMPLANTS)
            .addValidAugment(HumanAugments.TEETH_VENEERS)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_HANDS = PhysicalAspect.Builder(BodyPart.HANDS, "human_hands", "Human Hands", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(HumanGeneProperties.HUMAN_WRINKLE_AGE)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PARALYSIS)
            .build();
    public static final PhysicalAspect HUMAN_FEET = PhysicalAspect.Builder(BodyPart.FEET, "human_feet", "Human Feet", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(HumanGeneProperties.HUMAN_WRINKLE_AGE)
            .addValidAugment(CreatureAugments.SCARS)
            .addValidAugment(CreatureAugments.BURNS)
            .addValidAugment(CreatureAugments.TATTOOS)
            .addValidAugment(CreatureAugments.LOSS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.PARALYSIS)
            .build();
    public static final PhysicalAspect HUMAN_VITAL_ORGANS = PhysicalAspect.Builder(BodyPart.VITAL_ORGAN, "human_vital_organs", "Human Vital Organs", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_BRAIN = PhysicalAspect.Builder(BodyPart.BRAIN, "human_brain", "Human Brain", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidProperty(CreatureGeneProperties.INTELLECTUAL_DISABILITY)
            .addValidProperty(CreatureGeneProperties.MENTAL_ILLNESS)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.INJURY)
            .addValidAugment(CreatureAugments.MENTAL_ILLNESS)
            .addValidAugment(CreatureAugments.INTELLECTUAL_DISABILITY)
            .build();
    public static final PhysicalAspect HUMAN_IMMUNE_SYSTEM = PhysicalAspect.Builder(BodyPart.IMMUNE_SYSTEM, "human_immune_system", "Human Immune System", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.ILLNESS)
            .build();
    public static final PhysicalAspect HUMAN_DIGESTIVE = PhysicalAspect.Builder(BodyPart.DIGESTIVE_ORGAN, "human_digestive", "Human Digestive System", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
    public static final PhysicalAspect HUMAN_RESPIRATORY = PhysicalAspect.Builder(BodyPart.RESPIRATORY_ORGAN, "human_respiratory", "Human Respiratory System", "")
            .addValidProperty(CreatureGeneProperties.CONGENITAL_CONDITION)
            .addValidAugment(CreatureAugments.ILLNESS)
            .addValidAugment(CreatureAugments.INJURY)
            .build();
}