package com.objects.culture.tenet.group;

import com.Global.*;
import com.google.common.collect.ImmutableList;
import com.objects.culture.tenet.Acceptance;

import static com.objects.culture.tenet.group.EconomicGroups.ECONOMIC_SYSTEM;
import static com.objects.culture.tenet.group.EconomicGroups.ECONOMY;
import static com.objects.culture.tenet.group.EducationGroups.EDUCATION;
import static com.objects.culture.tenet.group.Family.FAMILY;
import static com.objects.culture.tenet.group.ReligionGroups.RELIGION;
import static com.objects.culture.tenet.group.SocietyGroups.SOCIETY;
import static com.objects.culture.tenet.group.TenetGroup.*;

public class GovernmentGroups {

    public static final TenetGroup GOVERNMENT = builder(HARD_CULTURE, "government", "Government", "The political institutions and systems through which authority is exercised, laws are made, and public order maintained.", SORT_ONLY);
    public static final TenetGroup GOVERNMENT_SYSTEM = builder(GOVERNMENT, "system", "Government System", "The formal structure of political authority—how power is organized, distributed, and exercised across institutions.", PILLAR);
    public static final TenetGroup GOVERNMENT_IDEOLOGY = builder(GOVERNMENT, ImmutableList.of(GOVERNMENT_SYSTEM), "ideology", "Government Ideology", "The political values and beliefs that shape governing priorities, from individual liberty and equality to order and hierarchy.", PILLAR);

    public static final TenetGroup RESOURCE_ALLOCATION = builder(GOVERNMENT_SYSTEM, ImmutableList.of(ECONOMIC_SYSTEM), "resource_allocation", "Resource Allocation", "How the government collects and distributes public funds across welfare, military, education, and other state functions.", SYSTEM_LARGE);
    public static final TenetGroup WELFARE = builder(RESOURCE_ALLOCATION, "welfare", "Welfare", "State support for citizens in need, ranging from minimal safety nets to comprehensive programs covering housing, food, and health.", SYSTEM_LARGE);
    public static final TenetGroup TAXATION = builder(RESOURCE_ALLOCATION, "taxation", "Taxation", "The system by which the state raises revenue from individuals and institutions, including rates, methods, and exemptions.", SYSTEM_LARGE);
    public static final TenetGroup ECONOMIC_INTERVENTION = builder(RESOURCE_ALLOCATION, ImmutableList.of(ECONOMY), "economic_intervention", "Economic Intervention", "The degree to which the government shapes economic activity through regulation, subsidies, state ownership, or central planning.", SYSTEM_LARGE);
    public static final TenetGroup EDUCATION_FUNDING = builder(RESOURCE_ALLOCATION, ImmutableList.of(EDUCATION), "education_funding", "Education Intervention", "Government spending on education, determining access, quality, and the balance between public provision and private schooling.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_FUNDING = builder(RESOURCE_ALLOCATION, "military_funding", "Military Funding", "The allocation of public resources to the armed forces, shaping their size, readiness, and operational capacity.", SYSTEM_LARGE);
    public static final TenetGroup JUSTICE_SYSTEM = builder(GOVERNMENT_SYSTEM, "justice_system", "Justice System", "The legal institutions and processes by which crimes are defined, tried, and punished, including courts, law enforcement, and prisons.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_CORRUPTION = builder(JUSTICE_SYSTEM, "corruption", "Corruption", "The abuse of public office for private gain, from petty bribery to systemic capture of state institutions by factional interests.", SYSTEM_LARGE);
    public static final TenetGroup CLASS_AND_CASTE = builder(GOVERNMENT_SYSTEM, ImmutableList.of(WELFARE, TAXATION), "class_and_caste", "Class and Caste", "The formal and informal hierarchies dividing society into strata with different rights, duties, and access to political power.", SYSTEM_LARGE);
    public static final TenetGroup CIVIL_LIBERTIES = builder(GOVERNMENT_SYSTEM, ImmutableList.of(JUSTICE_SYSTEM, CLASS_AND_CASTE), "civil_rights", "Civil Rights", "The individual rights and freedoms protected from government interference, including speech, assembly, religion, and due process.", SYSTEM_LARGE);
    public static final TenetGroup CITIZENSHIP = builder(CLASS_AND_CASTE, "citizenship", "Citizenship", "The legal status conferring membership in the polity and the rights, privileges, and obligations that come with it.", SYSTEM_LARGE);
    public static final TenetGroup ELITE = builder(CLASS_AND_CASTE, ImmutableList.of(CITIZENSHIP), "elites", "Elites", "Those at the apex of society—landed, wealthy, or noble—and the privileges, duties, and vulnerabilities attached to that status.", SYSTEM_LARGE);
    public static final TenetGroup MIDDLE_CLASS = builder(CLASS_AND_CASTE, ImmutableList.of(CITIZENSHIP), "middle_class", "Middle Class", "The broad stratum between elites and laborers, whose prosperity, aspirations, and political weight shape civic life.", SYSTEM_LARGE);
    public static final TenetGroup SOLDIER = builder(CLASS_AND_CASTE, ImmutableList.of(CITIZENSHIP), "soldiers", "Soldiers", "Soldiers as a formal social class—their legal status, civic rights, and standing relative to other groups within society.", SYSTEM_LARGE);
    public static final TenetGroup WORKING_CLASS = builder(CLASS_AND_CASTE, ImmutableList.of(CITIZENSHIP), "working_class", "Working Class", "Laborers and manual workers who form the productive base of society, their rights, living conditions, and political voice.", SYSTEM_LARGE);
    public static final TenetGroup DISENFRANCHISED = builder(CLASS_AND_CASTE, "disenfranchised", "Disenfranchised", "Those stripped of political rights and social standing—serfs, convicts, ethnic minorities—and how the state treats them.", SYSTEM_LARGE);
    public static final TenetGroup OUTSIDER = builder(CLASS_AND_CASTE, ImmutableList.of(CITIZENSHIP), "outsider", "Outsiders and Foreigners", "Foreigners, immigrants, and those of alien origin living within the state, and how they are treated, integrated, or excluded.", SYSTEM_LARGE);
    public static final TenetGroup FOREIGN_POLICY = builder(GOVERNMENT_SYSTEM, "foreign_policy", "Foreign Policy", "The principles and policies governing how the state conducts relations with other nations, from diplomacy and trade to open conflict.", SYSTEM_LARGE);

    public static final TenetGroup MILITARY = builder(GOVERNMENT_SYSTEM, ImmutableList.of(MILITARY_FUNDING), "military", "Military", "The armed forces of the state, encompassing their structure, doctrine, ethics, and relationship to civil society and government.", PILLAR);
    public static final TenetGroup MILITARY_INFLUENCE_ON_GOVERNMENT = builder(MILITARY, ImmutableList.of(CLASS_AND_CASTE, MILITARY), "military_influence", "Military Influence on Government", "The degree to which military institutions shape or control civilian governance, from advisory roles to outright political dominance.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_LOGISTICS = builder(MILITARY, ImmutableList.of(MILITARY_FUNDING), "logistics", "Military Logistics", "The systems for supplying, equipping, and sustaining armed forces in peace and war, from recruitment to procurement.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_RECRUITMENT = builder(MILITARY_LOGISTICS, ImmutableList.of(MILITARY_FUNDING), "recruitment", "Military Recruitment", "How soldiers enter service—through conscription, voluntary enlistment, or mercenary hire—and the standards applied to each.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_TRAINING = builder(MILITARY_LOGISTICS, ImmutableList.of(MILITARY_FUNDING), "training", "Military Training", "The methods and standards used to prepare soldiers for combat, from basic discipline to specialized and elite warfare skills.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_EQUIPMENT = builder(MILITARY_LOGISTICS, ImmutableList.of(MILITARY_FUNDING), "equipment", "Military Equipment and Logistics", "The weapons, armor, and materiel supplied to armed forces, and the systems used to maintain and replace them in the field.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_PROCUREMENT = builder(MILITARY_LOGISTICS, ImmutableList.of(MILITARY_EQUIPMENT), "procurement", "Military Procurement", "The processes by which the military acquires equipment and supplies, including contracts, oversight, and vulnerability to corruption.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_WOUNDED_AND_VETERANS = builder(MILITARY, "wounded_and_veterans", "Military Wounded and Veterans", "The treatment of soldiers injured in service and those who have completed their duty, including care, recognition, and reintegration.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_UPWARD_MOBILITY = builder(MILITARY, "upward_mobility", "Military Upward Mobility", "The paths by which soldiers and officers can advance in rank and social standing through military service and distinction.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_POLICY = builder(MILITARY, "ethics", "Military Policy and Doctrine", "The rules, doctrines, and ethical frameworks governing how the military operates, both in the field and at home.", SORT_ONLY);
    public static final TenetGroup SOLDIER_TREATMENT = builder(MILITARY_POLICY, ImmutableList.of(MILITARY_FUNDING, MILITARY_LOGISTICS, SOLDIER), "soldier_treatment", "Soldier Treatment", "How enlisted soldiers are fed, housed, paid, and regarded by their commanders and the state during and after service.", SYSTEM_LARGE);
    public static final TenetGroup SPECIAL_OPERATIONS = builder(MILITARY_POLICY, ImmutableList.of(MILITARY_LOGISTICS), "special_operations", "Special Operations", "Elite units operating beyond conventional warfare—conducting raids, sabotage, and covert missions with specialized training and authority.", SYSTEM_LARGE);
    public static final TenetGroup ORDER_OF_BATTLE = builder(MILITARY_POLICY, ImmutableList.of(MILITARY_LOGISTICS), "order_of_battle", "Order of Battle", "The organizational structure of military forces, including unit composition, hierarchy, and the distribution of arms and roles.", SYSTEM_LARGE);
    public static final TenetGroup COMBAT_DOCTRINE = builder(MILITARY_POLICY, ImmutableList.of(MILITARY_LOGISTICS), "combat_doctrine", "Combat Doctrine", "The tactical and strategic principles guiding how the military fights, from offensive aggression to defensive depth and maneuver.", SYSTEM_LARGE);
    public static final TenetGroup RULES_OF_ENGAGEMENT = builder(MILITARY_POLICY, "use_of_force", "Use of Force", "The guidelines governing when and how force may be used, shaping conduct toward enemies, civilians, and prisoners of war.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_JUSTICE = builder(MILITARY_POLICY, ImmutableList.of(JUSTICE_SYSTEM), "military_justice", "Military Justice", "The legal system governing soldiers' conduct and discipline, from courts-martial to punishment for desertion and war crimes.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_INTERVENTION_IN_CIVIL_LIFE = builder(MILITARY_POLICY, ImmutableList.of(JUSTICE_SYSTEM, CIVIL_LIBERTIES, COMBAT_DOCTRINE, RULES_OF_ENGAGEMENT), "intervention_in_civil_life", "Military Intervention in Civil Life", "The use of military force within the state's own borders—for disaster response, policing, or the suppression of dissent.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_INTERVENTION_IN_FOREIGN_CONFLICT = builder(MILITARY_POLICY, ImmutableList.of(FOREIGN_POLICY, COMBAT_DOCTRINE, RULES_OF_ENGAGEMENT), "intervention_in_foreign_conflict", "Military Intervention in Foreign Conflict", "The conditions and limits on deploying military force abroad, from defense of allies to preemptive strikes and occupations.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_LEADERSHIP = builder(MILITARY, "leadership", "Military Leadership", "The structures and norms through which officers are selected, promoted, and removed, shaping command culture and accountability.", SORT_ONLY);
    public static final TenetGroup CENTRALIZATION = builder(MILITARY_LEADERSHIP, ImmutableList.of(COMBAT_DOCTRINE, ORDER_OF_BATTLE, MILITARY_UPWARD_MOBILITY, RULES_OF_ENGAGEMENT), "command_centralization", "Command Centralization", "How tightly command authority is held at the top versus delegated to field commanders throughout the chain of command.", SYSTEM_LARGE);
    public static final TenetGroup OFFICER_APPOINTMENT = builder(MILITARY_LEADERSHIP, ImmutableList.of(CENTRALIZATION, MILITARY_RECRUITMENT, MILITARY_UPWARD_MOBILITY), "officer_appointment", "Officer Appointment", "The criteria and processes by which officers are selected for command—merit, patronage, election, or hereditary right.", SYSTEM_LARGE);
    public static final TenetGroup OFFICER_REMOVAL = builder(MILITARY_LEADERSHIP, ImmutableList.of(MILITARY_JUSTICE), "officer_removal", "Officer Removal", "The circumstances and procedures under which officers may be dismissed, demoted, or punished for failures or misconduct.", SYSTEM_LARGE);
    public static final TenetGroup OFFICER_TREATMENT = builder(MILITARY_LEADERSHIP, ImmutableList.of(MILITARY_FUNDING), "officer_treatment", "Officer Treatment", "How officers are compensated, housed, and regarded by the state and their subordinates during and after their service.", SYSTEM_LARGE);
    public static final TenetGroup OFFICER_TRAINING = builder(MILITARY_LEADERSHIP, ImmutableList.of(MILITARY_FUNDING, MILITARY_TRAINING), "officer_training", "Officer Training", "The education and preparation given to officers in leadership, tactics, and administration beyond basic soldiering skills.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_IDEOLOGY = builder(MILITARY, "ideology", "Military Ideology", "The beliefs and values defining the military's identity, mission, and relationship to the state and the society it serves.", SORT_ONLY);
    public static final TenetGroup MILITARY_SELF_CONCEPT = builder(MILITARY_IDEOLOGY, "self_concept", "Military Self-Concept", "How the military understands its own purpose and character—guardian of the nation, instrument of the state, or independent institution.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_IDEOLOGICAL_CAPTURE = builder(MILITARY_IDEOLOGY, "ideological_capture", "Military Ideological Capture", "The degree to which a political ideology, faction, or religion has embedded itself within the military's culture and loyalty.", SYSTEM_LARGE);
    public static final TenetGroup SOLDIER_VALUE = builder(MILITARY_IDEOLOGY, ImmutableList.of(MILITARY_UPWARD_MOBILITY), "soldier_value", "Soldier Value", "The traits a military culture admires or condemns in its rank-and-file—obedience, courage, initiative, or brutality.", SYSTEM_LARGE);
    public static final TenetGroup OFFICER_VALUE = builder(MILITARY_IDEOLOGY, ImmutableList.of(MILITARY_UPWARD_MOBILITY, CENTRALIZATION), "officer_value", "Officer Value", "The traits a military culture admires or condemns in its officers—honor, cunning, loyalty, ambition, or ruthlessness.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_HEROES_AND_VILLAINS = builder(MILITARY_IDEOLOGY, "heroes_and_villains", "Heroes and Villains", "The historical and mythic figures the military venerates or condemns, shaping its collective identity and moral standards.", SYSTEM_LARGE);
    public static final TenetGroup MILITARY_LOYALTY = builder(MILITARY, ImmutableList.of(MILITARY_JUSTICE, MILITARY_IDEOLOGICAL_CAPTURE, MILITARY_SELF_CONCEPT, OFFICER_TREATMENT, SOLDIER_TREATMENT), "loyalty", "Military Loyalty", "The bonds of allegiance within the military—to state, leader, institution, or ideology—and what strains or breaks them.", SORT_ONLY);
    public static final TenetGroup MILITARY_CORRUPTION = builder(MILITARY, ImmutableList.of(GOVERNMENT_CORRUPTION, MILITARY_JUSTICE, MILITARY_IDEOLOGICAL_CAPTURE, MILITARY_SELF_CONCEPT, OFFICER_TREATMENT, SOLDIER_TREATMENT, MILITARY_LOYALTY), "corruption", "Military Corruption", "Misconduct within the military for personal gain, from theft of supplies to officer nepotism and defense contract fraud.", SYSTEM_LARGE);

    public static final TenetGroup GOVERNMENT_LEADERSHIP = builder(GOVERNMENT_SYSTEM, ImmutableList.of(CLASS_AND_CASTE, MILITARY), "leadership", "Leadership", "The structures and norms governing how the head of state and senior leaders are selected, empowered, and removed.", SORT_ONLY);
    public static final TenetGroup LEADERSHIP_SELECTION = builder(GOVERNMENT_LEADERSHIP, ImmutableList.of(CLASS_AND_CASTE, DISENFRANCHISED), "selection", "Leadership Selection", "How the head of government comes to power—through election, inheritance, military coup, appointment, or divine right.", SYSTEM_LARGE);
    public static final TenetGroup LEADER_AUTHORITY = builder(GOVERNMENT_LEADERSHIP, "authority", "Leader Authority", "The scope and limits of power held by the head of government, from constitutional constraints to absolute and unaccountable rule.", SYSTEM_LARGE);
    public static final TenetGroup LEADER_CORRUPTION = builder(GOVERNMENT_LEADERSHIP, ImmutableList.of(GOVERNMENT_CORRUPTION, LEADER_AUTHORITY), "corruption", "Leader Corruption", "The abuse of power by the head of government for personal enrichment, dynastic advantage, or factional benefit.", SYSTEM_LARGE);
    public static final TenetGroup LEADERSHIP_REMOVAL = builder(GOVERNMENT_LEADERSHIP, ImmutableList.of(LEADER_CORRUPTION), "removal", "Leadership Removal", "How leaders may be removed from power—through elections, impeachment, revolution, abdication, or death in office.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_OFFICE = builder(GOVERNMENT_SYSTEM, "office", "Government Office", "The formal positions and institutions through which government functions are carried out below the level of top leadership.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_OFFICE_AUTHORITY = builder(GOVERNMENT_OFFICE, "authority", "Government Office Authority", "The powers granted to government offices and the limits placed on their action by law, tradition, or political will.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_OFFICE_CREATION_REMOVAL = builder(GOVERNMENT_OFFICE, "creation_removal", "Government Office Creation and Removal", "The processes by which new government offices are established or existing ones abolished, restructured, or consolidated.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_OFFICIAL = builder(GOVERNMENT_OFFICE, ImmutableList.of(MILITARY), "official", "Government Official", "The individuals who hold formal government positions, encompassing their selection, authority, treatment, and accountability.", SORT_ONLY);
    public static final TenetGroup OFFICIAL_SELECTION = builder(GOVERNMENT_OFFICIAL, ImmutableList.of(CLASS_AND_CASTE, DISENFRANCHISED), "selection", "Selection of an Official", "The criteria and processes by which government officials are appointed—merit, patronage, hereditary right, or election.", SYSTEM_LARGE);
    public static final TenetGroup OFFICIAL_AUTHORITY = builder(GOVERNMENT_OFFICIAL, "authority", "An Official's Authority", "The powers and discretion available to individual officials in carrying out their duties within the state apparatus.", SYSTEM_LARGE);
    public static final TenetGroup OFFICIAL_TREATMENT_GOVERNMENT = builder(GOVERNMENT_OFFICIAL, "treatment_government", "An Official's Treatment by the Government", "How the state compensates, protects, and regards the officials who serve it, including pay, prestige, and tenure.", SYSTEM_LARGE);
    public static final TenetGroup OFFICIAL_TREATMENT_PEOPLE = builder(GOVERNMENT_OFFICIAL, "treatment_people", "An Official's Treatment by the People", "How citizens and subjects relate to and treat government officials—with deference, suspicion, bribery, or open hostility.", SYSTEM_LARGE);
    public static final TenetGroup OFFICIAL_CORRUPTION = builder(GOVERNMENT_OFFICIAL, ImmutableList.of(GOVERNMENT_CORRUPTION, OFFICIAL_AUTHORITY, OFFICIAL_TREATMENT_GOVERNMENT, OFFICIAL_TREATMENT_PEOPLE), "corruption", "Corruption among Officials", "The abuse of official position for personal or factional gain, from accepting bribes to embezzlement and administrative fraud.", SYSTEM_LARGE);
    public static final TenetGroup OFFICIAL_REMOVAL = builder(GOVERNMENT_OFFICIAL, ImmutableList.of(OFFICIAL_AUTHORITY, CLASS_AND_CASTE, DISENFRANCHISED), "removal", "Removal of an Official", "The processes and conditions under which officials may be dismissed, demoted, or held accountable for misconduct or failure.", SYSTEM_LARGE);
    public static final TenetGroup SOFT_CULTURE_INTERVENTION = builder(GOVERNMENT_OFFICIAL, ImmutableList.of(SOFT_CULTURE), "soft_culture_interventionalism", "Soft Culture Intervention", "The extent to which the government shapes or controls religion, society, family, and education through law and active policy.", SORT_ONLY);
    public static final TenetGroup SECULARISM = builder(SOFT_CULTURE_INTERVENTION, ImmutableList.of(RELIGION, GOVERNMENT_LEADERSHIP), "secularism", "Secularism", "The separation of religious institutions from state power, ranging from strict neutrality to active suppression of faith in public life.", SYSTEM_LARGE);
    public static final TenetGroup GOVERNMENT_ENFORCED_CONFORMITY = builder(SOFT_CULTURE_INTERVENTION, ImmutableList.of(CIVIL_LIBERTIES, CLASS_AND_CASTE), "culture_war", "Conformity", "Laws and mechanisms compelling social, cultural, or ideological conformity, from dress codes to persecution of dissent.", SYSTEM_LARGE);
    public static final TenetGroup EDUCATION_INTERVENTION = builder(SOFT_CULTURE_INTERVENTION, ImmutableList.of(EDUCATION, EDUCATION_FUNDING), "education_funding", "Education Intervention", "The degree to which the state directs educational content, access, and structure, from curriculum oversight to school nationalization.", SYSTEM_LARGE);
    public static final TenetGroup FAMILY_INTERVENTION = builder(SOFT_CULTURE_INTERVENTION, ImmutableList.of(FAMILY), "family_intervention", "Family Intervention", "The extent to which the state regulates family structure, marriage, reproduction, and the raising of children.", SYSTEM_LARGE);
    public static final TenetGroup ESPIONAGE = builder(GOVERNMENT_SYSTEM, ImmutableList.of(MILITARY, CIVIL_LIBERTIES, JUSTICE_SYSTEM), "espionage", "Espionage", "Intelligence and covert activities conducted to protect the state, surveil its enemies, and operate beyond the reach of public law.", SORT_ONLY);
    public static final TenetGroup SECRET_POLICE = builder(ESPIONAGE, ImmutableList.of(SOCIETY), "secret_police", "Secret Police & Mass Surveillance", "State security organs that surveil, infiltrate, and suppress internal dissent, operating with varying oversight and transparency.", SYSTEM_LARGE);
    public static final TenetGroup FOREIGN_INTELLIGENCE_SERVICE = builder(ESPIONAGE, ImmutableList.of(FOREIGN_POLICY), "foreign_intelligence_service", "Foreign Intelligence Service", "Agencies gathering intelligence on foreign states, militaries, and movements to inform national strategy and protect state interests.", SYSTEM_LARGE);
    public static final TenetGroup COVERT_OPERATIONS = builder(ESPIONAGE, ImmutableList.of(SPECIAL_OPERATIONS), "covert_operations", "Covert Operations", "Clandestine actions abroad—sabotage, assassination, influence campaigns—advancing state interests while preserving deniability.", SYSTEM_LARGE);
    public static final TenetGroup ACCOUNTABILITY = builder(ESPIONAGE, ImmutableList.of(GOVERNMENT_LEADERSHIP, GOVERNMENT_CORRUPTION), "accountability", "Accountability", "The mechanisms by which intelligence and security agencies are overseen and held accountable, from parliamentary review to total secrecy.", SYSTEM_LARGE);

    // Government Value Children
    public static final TenetGroup GOVERNMENT_VALUE = builder(GOVERNMENT_IDEOLOGY, "value", "Government Value", "The traits a society admires or condemns in its government—just, corrupt, strong, distant, protective, or tyrannical.", new AcceptanceContainer(3, Acceptance.CORE, Acceptance.CORE_FANATIC));
    public static final TenetGroup GOVERNMENT_HEROES_AND_VILLANS = builder(GOVERNMENT_IDEOLOGY, "heroes_and_villains", "Heroes and Villains", "The rulers, reformers, and traitors a society celebrates or condemns, shaping civic memory and political identity.", new AcceptanceContainer(3, Acceptance.CORE, Acceptance.CORE_FANATIC), new AcceptanceContainer(5, Acceptance.INTEGRATED));



    public static void init() {

    }
}
