package com.objects.character.physical.species.carnivora;

import com.Global.*;
import com.objects.character.physical.species.Species;
import com.objects.character.physical.species.nomenclature.AnimalNameContainers;

import static com.objects.character.physical.species.carnivora.Canidae.*;
import static com.objects.character.physical.species.carnivora.Mustelidae.*;
import static com.objects.character.physical.species.carnivora.Ursidae.*;

public class CarnivoraSpecies {

    public static final Species GRIZZLY_BEAR = Species.builder("grizzly_bear", "Ursus Arctos Horribilis", "Grizzly Bear")
            .addValidProperty(URSIDAE_BODY)
            .addValidProperty(URSIDAE_SKIN)
            .addValidProperty(URSIDAE_FUR)
            .addValidProperty(URSIDAE_HEAD)
            .addValidProperty(URSIDAE_EYES)
            .addValidProperty(URSIDAE_EARS)
            .addValidProperty(URSIDAE_NOSE)
            .addValidProperty(URSIDAE_MOUTH)
            .addValidProperty(URSIDAE_NECK)
            .addValidProperty(URSIDAE_TORSO)
            .addValidProperty(URSIDAE_BACK)
            .addValidProperty(URSIDAE_FRONT_PAWS)
            .addValidProperty(URSIDAE_REAR_PAWS)
            .addValidProperty(URSIDAE_BRAIN)
            .addValidProperty(URSIDAE_VITAL_ORGANS)
            .addValidProperty(URSIDAE_IMMUNE_SYSTEM)
            .addValidProperty(URSIDAE_DIGESTIVE)
            .addValidProperty(URSIDAE_RESPIRATORY)
            .addValidProperty(URSIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(55)
            .setNomenclature(AnimalNameContainers.GRIZZLY_BEAR)
            .setLifeExpectancy(25)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(5)
            .setAgeOfElderly(20)
            .setAgeOfInfertilityMale(23)
            .setAgeOfInfertilityFemale(22)
            .addGenderRatio(URSIDAE_BODY_SIZE, 1.5f)
            .build();

    public static final Species CALIFORNIA_GRIZZLY = Species.builder("california_grizzly", "Ursus Arctos Californicus", "California Grizzly")
            .addValidProperty(URSIDAE_BODY)
            .addValidProperty(URSIDAE_SKIN)
            .addValidProperty(URSIDAE_FUR)
            .addValidProperty(URSIDAE_HEAD)
            .addValidProperty(URSIDAE_EYES)
            .addValidProperty(URSIDAE_EARS)
            .addValidProperty(URSIDAE_NOSE)
            .addValidProperty(URSIDAE_MOUTH)
            .addValidProperty(URSIDAE_NECK)
            .addValidProperty(URSIDAE_TORSO)
            .addValidProperty(URSIDAE_BACK)
            .addValidProperty(URSIDAE_FRONT_PAWS)
            .addValidProperty(URSIDAE_REAR_PAWS)
            .addValidProperty(URSIDAE_BRAIN)
            .addValidProperty(URSIDAE_VITAL_ORGANS)
            .addValidProperty(URSIDAE_IMMUNE_SYSTEM)
            .addValidProperty(URSIDAE_DIGESTIVE)
            .addValidProperty(URSIDAE_RESPIRATORY)
            .addValidProperty(URSIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(55)
            .setNomenclature(AnimalNameContainers.CALIFORNIA_GRIZZLY)
            .setLifeExpectancy(25)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(5)
            .setAgeOfElderly(20)
            .setAgeOfInfertilityMale(23)
            .setAgeOfInfertilityFemale(22)
            .addGenderRatio(URSIDAE_BODY_SIZE, 1.5f)
            .build();

    public static final Species BLACK_BEAR = Species.builder("black_bear", "Ursus Americanus Americanus", "Black Bear")
            .addValidProperty(URSIDAE_BODY)
            .addValidProperty(URSIDAE_SKIN)
            .addValidProperty(URSIDAE_FUR)
            .addValidProperty(URSIDAE_HEAD)
            .addValidProperty(URSIDAE_EYES)
            .addValidProperty(URSIDAE_EARS)
            .addValidProperty(URSIDAE_NOSE)
            .addValidProperty(URSIDAE_MOUTH)
            .addValidProperty(URSIDAE_NECK)
            .addValidProperty(URSIDAE_TORSO)
            .addValidProperty(URSIDAE_BACK)
            .addValidProperty(URSIDAE_FRONT_PAWS)
            .addValidProperty(URSIDAE_REAR_PAWS)
            .addValidProperty(URSIDAE_BRAIN)
            .addValidProperty(URSIDAE_VITAL_ORGANS)
            .addValidProperty(URSIDAE_IMMUNE_SYSTEM)
            .addValidProperty(URSIDAE_DIGESTIVE)
            .addValidProperty(URSIDAE_RESPIRATORY)
            .addValidProperty(URSIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(55)
            .setNomenclature(AnimalNameContainers.BLACK_BEAR)
            .setLifeExpectancy(18)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(3)
            .setAgeOfElderly(15)
            .setAgeOfInfertilityMale(17)
            .setAgeOfInfertilityFemale(16)
            .addGenderRatio(URSIDAE_BODY_SIZE, 1.5f)
            .build();

    public static final Species POLAR_BEAR = Species.builder("polar_bear", "Ursus Maritimus Maritimus", "Polar Bear")
            .addValidProperty(URSIDAE_BODY)
            .addValidProperty(URSIDAE_SKIN)
            .addValidProperty(URSIDAE_FUR)
            .addValidProperty(URSIDAE_HEAD)
            .addValidProperty(URSIDAE_EYES)
            .addValidProperty(URSIDAE_EARS)
            .addValidProperty(URSIDAE_NOSE)
            .addValidProperty(URSIDAE_MOUTH)
            .addValidProperty(URSIDAE_NECK)
            .addValidProperty(URSIDAE_TORSO)
            .addValidProperty(URSIDAE_BACK)
            .addValidProperty(URSIDAE_FRONT_PAWS)
            .addValidProperty(URSIDAE_REAR_PAWS)
            .addValidProperty(URSIDAE_BRAIN)
            .addValidProperty(URSIDAE_VITAL_ORGANS)
            .addValidProperty(URSIDAE_IMMUNE_SYSTEM)
            .addValidProperty(URSIDAE_DIGESTIVE)
            .addValidProperty(URSIDAE_RESPIRATORY)
            .addValidProperty(URSIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(55)
            .setNomenclature(AnimalNameContainers.POLAR_BEAR)
            .setLifeExpectancy(25)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(4)
            .setAgeOfElderly(20)
            .setAgeOfInfertilityMale(23)
            .setAgeOfInfertilityFemale(20)
            .addGenderRatio(URSIDAE_BODY_SIZE, 1.5f)
            .build();

    public static final Species NA_RIVER_OTTER = Species.builder("na_river_otter", "Lontra Canadensis Canadensis", "North American River Otter")
            .addValidProperty(MUSTELIDAE_BODY)
            .addValidProperty(MUSTELIDAE_SKIN)
            .addValidProperty(MUSTELIDAE_FUR)
            .addValidProperty(MUSTELIDAE_HEAD)
            .addValidProperty(MUSTELIDAE_EYES)
            .addValidProperty(MUSTELIDAE_EARS)
            .addValidProperty(MUSTELIDAE_NOSE)
            .addValidProperty(MUSTELIDAE_MOUTH)
            .addValidProperty(MUSTELIDAE_WHISKERS)
            .addValidProperty(MUSTELIDAE_NECK)
            .addValidProperty(MUSTELIDAE_TORSO)
            .addValidProperty(MUSTELIDAE_BACK)
            .addValidProperty(MUSTELIDAE_TAIL)
            .addValidProperty(MUSTELIDAE_FRONT_PAWS)
            .addValidProperty(MUSTELIDAE_REAR_PAWS)
            .addValidProperty(MUSTELIDAE_BRAIN)
            .addValidProperty(MUSTELIDAE_VITAL_ORGANS)
            .addValidProperty(MUSTELIDAE_IMMUNE_SYSTEM)
            .addValidProperty(MUSTELIDAE_DIGESTIVE)
            .addValidProperty(MUSTELIDAE_RESPIRATORY)
            .addValidProperty(MUSTELIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(45)
            .setNomenclature(AnimalNameContainers.NA_RIVER_OTTER)
            .setLifeExpectancy(8)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(6)
            .setAgeOfInfertilityMale(8)
            .setAgeOfInfertilityFemale(7)
            .addGenderRatio(MUSTELIDAE_BODY_SIZE, 1.25f)
            .build();

    public static final Species NA_OCEAN_OTTER = Species.builder("na_ocean_otter", "Enhydra Lutris Kenyoni", "North American Sea Otter")
            .addValidProperty(MUSTELIDAE_BODY)
            .addValidProperty(MUSTELIDAE_SKIN)
            .addValidProperty(MUSTELIDAE_FUR)
            .addValidProperty(MUSTELIDAE_HEAD)
            .addValidProperty(MUSTELIDAE_EYES)
            .addValidProperty(MUSTELIDAE_EARS)
            .addValidProperty(MUSTELIDAE_NOSE)
            .addValidProperty(MUSTELIDAE_MOUTH)
            .addValidProperty(MUSTELIDAE_WHISKERS)
            .addValidProperty(MUSTELIDAE_NECK)
            .addValidProperty(MUSTELIDAE_TORSO)
            .addValidProperty(MUSTELIDAE_BACK)
            .addValidProperty(MUSTELIDAE_TAIL)
            .addValidProperty(MUSTELIDAE_FRONT_PAWS)
            .addValidProperty(MUSTELIDAE_REAR_PAWS)
            .addValidProperty(MUSTELIDAE_BRAIN)
            .addValidProperty(MUSTELIDAE_VITAL_ORGANS)
            .addValidProperty(MUSTELIDAE_IMMUNE_SYSTEM)
            .addValidProperty(MUSTELIDAE_DIGESTIVE)
            .addValidProperty(MUSTELIDAE_RESPIRATORY)
            .addValidProperty(MUSTELIDAE_REPRODUCTIVE)
            .setMagicCapacity(0)
            .setSentience(48)
            .setNomenclature(AnimalNameContainers.NA_OCEAN_OTTER)
            .setLifeExpectancy(15)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(3)
            .setAgeOfElderly(12)
            .setAgeOfInfertilityMale(14)
            .setAgeOfInfertilityFemale(13)
            .addGenderRatio(MUSTELIDAE_BODY_SIZE, 1.25f)
            .build();
    public static final Species CANIDAE_GREY = Species.builder("CANIDAE_grey", "Canis Lupus Occidentalis", "Grey Wolf")
            .addValidProperty(CANIDAE_BODY)
            .addValidProperty(CANIDAE_SKIN)
            .addValidProperty(CANIDAE_FUR)
            .addValidProperty(CANIDAE_HEAD)
            .addValidProperty(CANIDAE_EYES)
            .addValidProperty(CANIDAE_EARS)
            .addValidProperty(CANIDAE_NOSE)
            .addValidProperty(CANIDAE_MOUTH)
            .addValidProperty(CANIDAE_NECK)
            .addValidProperty(CANIDAE_TORSO)
            .addValidProperty(CANIDAE_BACK)
            .addValidProperty(CANIDAE_TAIL)
            .addValidProperty(CANIDAE_FRONT_PAWS)
            .addValidProperty(CANIDAE_REAR_PAWS)
            .addValidProperty(CANIDAE_BRAIN)
            .addValidProperty(CANIDAE_VITAL_ORGANS)
            .addValidProperty(CANIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CANIDAE_DIGESTIVE)
            .addValidProperty(CANIDAE_RESPIRATORY)
            .addValidProperty(CANIDAE_REPRODUCTIVE)
            .setMagicCapacity(70)
            .setSentience(42)
            .setNomenclature(AnimalNameContainers.WOLF_GREY)
            .setLifeExpectancy(7)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(5)
            .setAgeOfInfertilityMale(9)
            .setAgeOfInfertilityFemale(7)
            .addGenderRatio(CANINE_BODY_SIZE, 1.15f)
            .build();

    public static final Species CANIDAE_TIMBER = Species.builder("CANIDAE_timber", "Canis Lupus Lycaon", "Timber Wolf")
            .addValidProperty(CANIDAE_BODY)
            .addValidProperty(CANIDAE_SKIN)
            .addValidProperty(CANIDAE_FUR)
            .addValidProperty(CANIDAE_HEAD)
            .addValidProperty(CANIDAE_EYES)
            .addValidProperty(CANIDAE_EARS)
            .addValidProperty(CANIDAE_NOSE)
            .addValidProperty(CANIDAE_MOUTH)
            .addValidProperty(CANIDAE_NECK)
            .addValidProperty(CANIDAE_TORSO)
            .addValidProperty(CANIDAE_BACK)
            .addValidProperty(CANIDAE_TAIL)
            .addValidProperty(CANIDAE_FRONT_PAWS)
            .addValidProperty(CANIDAE_REAR_PAWS)
            .addValidProperty(CANIDAE_BRAIN)
            .addValidProperty(CANIDAE_VITAL_ORGANS)
            .addValidProperty(CANIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CANIDAE_DIGESTIVE)
            .addValidProperty(CANIDAE_RESPIRATORY)
            .addValidProperty(CANIDAE_REPRODUCTIVE)
            .setMagicCapacity(70)
            .setSentience(42)
            .setNomenclature(AnimalNameContainers.WOLF_TIMBER)
            .setLifeExpectancy(8)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(6)
            .setAgeOfInfertilityMale(10)
            .setAgeOfInfertilityFemale(8)
            .addGenderRatio(CANINE_BODY_SIZE, 1.15f)
            .build();

    public static final Species CANIDAE_EURASIAN = Species.builder("CANIDAE_eurasian", "Canis Lupus Lupus", "Eurasian Wolf")
            .addValidProperty(CANIDAE_BODY)
            .addValidProperty(CANIDAE_SKIN)
            .addValidProperty(CANIDAE_FUR)
            .addValidProperty(CANIDAE_HEAD)
            .addValidProperty(CANIDAE_EYES)
            .addValidProperty(CANIDAE_EARS)
            .addValidProperty(CANIDAE_NOSE)
            .addValidProperty(CANIDAE_MOUTH)
            .addValidProperty(CANIDAE_NECK)
            .addValidProperty(CANIDAE_TORSO)
            .addValidProperty(CANIDAE_BACK)
            .addValidProperty(CANIDAE_TAIL)
            .addValidProperty(CANIDAE_FRONT_PAWS)
            .addValidProperty(CANIDAE_REAR_PAWS)
            .addValidProperty(CANIDAE_BRAIN)
            .addValidProperty(CANIDAE_VITAL_ORGANS)
            .addValidProperty(CANIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CANIDAE_DIGESTIVE)
            .addValidProperty(CANIDAE_RESPIRATORY)
            .addValidProperty(CANIDAE_REPRODUCTIVE)
            .setMagicCapacity(70)
            .setSentience(42)
            .setNomenclature(AnimalNameContainers.WOLF_EURASIAN)
            .setLifeExpectancy(9)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(6)
            .setAgeOfInfertilityMale(11)
            .setAgeOfInfertilityFemale(9)
            .addGenderRatio(CANINE_BODY_SIZE, 1.15f)
            .build();

    public static final Species CANIDAE_ARCTIC = Species.builder("CANIDAE_arctic", "Canis Lupus Arctos", "Arctic Wolf")
            .addValidProperty(CANIDAE_BODY)
            .addValidProperty(CANIDAE_SKIN)
            .addValidProperty(CANIDAE_FUR)
            .addValidProperty(CANIDAE_HEAD)
            .addValidProperty(CANIDAE_EYES)
            .addValidProperty(CANIDAE_EARS)
            .addValidProperty(CANIDAE_NOSE)
            .addValidProperty(CANIDAE_MOUTH)
            .addValidProperty(CANIDAE_NECK)
            .addValidProperty(CANIDAE_TORSO)
            .addValidProperty(CANIDAE_BACK)
            .addValidProperty(CANIDAE_TAIL)
            .addValidProperty(CANIDAE_FRONT_PAWS)
            .addValidProperty(CANIDAE_REAR_PAWS)
            .addValidProperty(CANIDAE_BRAIN)
            .addValidProperty(CANIDAE_VITAL_ORGANS)
            .addValidProperty(CANIDAE_IMMUNE_SYSTEM)
            .addValidProperty(CANIDAE_DIGESTIVE)
            .addValidProperty(CANIDAE_RESPIRATORY)
            .addValidProperty(CANIDAE_REPRODUCTIVE)
            .setMagicCapacity(70)
            .setSentience(42)
            .setNomenclature(AnimalNameContainers.WOLF_ARCTIC)
            .setLifeExpectancy(5)
            .setGenderLifeExpectancyRatio(1.0f)
            .setAgeOfMaturity(2)
            .setAgeOfElderly(4)
            .setAgeOfInfertilityMale(7)
            .setAgeOfInfertilityFemale(6)
            .addGenderRatio(CANINE_BODY_SIZE, 1.15f)
            .build();
}
